name: Contexto
run-name: Aprendiendo a usar contextos
on: push
jobs:
  check-main:
    if: ${{ github.ref == 'refs/head/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"
