name: Saludos con variables
run-name: Estoy aprendiendo a usar variables
on:
    workflow-dispatch
env:
    dia_semana: Miercoles
jobs:
  saludo_variables:
    runs-on: ubuntu-latest
    env:
      saludo: Hola
    steps:
      - name: Saludar con las vaiables
        run: echo "$saludo, ¿Cómo estás ${{ vars.NOMBRE }}? Hoy es día ${{ env.dia_semana }}"
  saludo-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Exponer secreto
        run: echo "$saludo, ${{ vars.NOMBRE }}. Tu contraseña es ${{ secrets.secreto_profundo }}.
      
